TEMPLATES: dict[str, list[dict]] = {
    "ransomware": [
        {"index": 0, "title": "Isolate affected hosts", "guidance": "Immediately disconnect affected endpoints from the network. Do not power off — preserve memory for forensics."},
        {"index": 1, "title": "Preserve memory and disk image", "guidance": "Capture volatile memory (RAM dump) and create forensic disk images before any remediation."},
        {"index": 2, "title": "Identify ransomware variant", "guidance": "Submit ransom note and a sample encrypted file to ID Ransomware (id-ransomware.malwarehunterteam.com) or VirusTotal."},
        {"index": 3, "title": "Assess blast radius", "guidance": "Determine which systems, shares, and backups are encrypted. Check shadow copies and backup integrity."},
        {"index": 4, "title": "Identify patient zero and entry vector", "guidance": "Trace the initial infection: phishing email, RDP brute force, exposed service, supply chain. Pull CySIEM logs."},
        {"index": 5, "title": "Notify stakeholders", "guidance": "Inform CISO, legal, and executive leadership. Assess if a regulatory notification is required (GDPR Art.33: 72h, NIS2 Art.23: 24h initial)."},
        {"index": 6, "title": "Check backup availability", "guidance": "Verify offline/immutable backup integrity. Confirm backup pre-dates infection. Do not restore until environment is clean."},
        {"index": 7, "title": "Eradicate and rebuild", "guidance": "Rebuild affected systems from clean images. Do not re-image over encrypted systems without forensic capture first."},
        {"index": 8, "title": "Restore from backup", "guidance": "Restore data from verified clean backups. Validate integrity post-restore."},
        {"index": 9, "title": "Post-incident review", "guidance": "Document timeline, root cause, actions taken. Update detection rules. Brief board/CISO. File regulatory notifications if required."},
    ],
    "phishing": [
        {"index": 0, "title": "Quarantine the phishing email", "guidance": "Use the email gateway to quarantine all copies of the email across all mailboxes matching the sender/subject/hash."},
        {"index": 1, "title": "Identify recipients and clickers", "guidance": "Determine who received and who clicked links or opened attachments. Pull mail server and proxy logs."},
        {"index": 2, "title": "Check for credential compromise", "guidance": "For any user who clicked: force password reset, revoke active sessions, check for MFA bypass, review recent login activity in CySIEM."},
        {"index": 3, "title": "Analyse the payload", "guidance": "Submit URLs and attachments to VirusTotal/sandbox. Extract IOCs (domains, IPs, file hashes). Add to case_iocs."},
        {"index": 4, "title": "Block IOCs", "guidance": "Block malicious domains and IPs at the proxy/firewall. Submit to MISP. Trigger CySOAR IOC block playbook."},
        {"index": 5, "title": "Check for lateral movement", "guidance": "Review CySIEM alerts for any post-click activity on affected hosts: new processes, outbound connections, lateral auth."},
        {"index": 6, "title": "Notify affected users", "guidance": "Inform users who interacted with the email. Provide guidance on what to report."},
        {"index": 7, "title": "Root cause and prevention", "guidance": "Why did the email bypass filters? Update SPF/DKIM/DMARC, email gateway rules. Consider phishing simulation follow-up."},
    ],
    "brute_force": [
        {"index": 0, "title": "Identify source IPs and targets", "guidance": "Pull all source IPs and targeted accounts from CySIEM. Check if IPs are known in MISP."},
        {"index": 1, "title": "Block source IPs", "guidance": "Block at perimeter firewall and/or trigger CySOAR brute-force block playbook. Confirm block is in place."},
        {"index": 2, "title": "Check for successful logins", "guidance": "Were any attempts successful? If yes, treat as potential account compromise — escalate checklist to phishing/lateral_movement."},
        {"index": 3, "title": "Lock targeted accounts if compromised", "guidance": "Force password reset and session revocation for any successfully authenticated accounts."},
        {"index": 4, "title": "Review exposed service", "guidance": "Is RDP/SSH/VPN/OWA exposed to the internet? Consider geo-blocking, port knocking, or moving behind VPN."},
        {"index": 5, "title": "Enable or verify MFA", "guidance": "Confirm MFA is enforced on the targeted service. If not, escalate as a gap finding to CyComp."},
        {"index": 6, "title": "Post-incident hardening", "guidance": "Document IP ranges, review account lockout policies, update detection thresholds in CySIEM."},
    ],
    "data_exfil": [
        {"index": 0, "title": "Identify exfiltration channel", "guidance": "Determine the protocol (HTTP/S, DNS, FTP, cloud sync) and destination. Pull proxy and DNS logs."},
        {"index": 1, "title": "Estimate data volume and type", "guidance": "How much data left? What classification? PII, credentials, IP? This determines regulatory notification obligation."},
        {"index": 2, "title": "Block the exfiltration channel", "guidance": "Block the destination IP/domain at the firewall. Terminate active sessions from the affected host."},
        {"index": 3, "title": "Isolate the source host", "guidance": "Remove the source endpoint from the network while preserving evidence."},
        {"index": 4, "title": "Identify how access was gained", "guidance": "Was this an insider, a compromised credential, or malware C2? Trace authentication logs."},
        {"index": 5, "title": "Assess regulatory notification", "guidance": "GDPR Art.33 (72h to supervisory authority), NIS2 Art.23 (24h initial), DORA Art.17 (classification within 4h). Notify legal."},
        {"index": 6, "title": "Preserve forensic evidence", "guidance": "Capture full disk image and network captures. Maintain chain of custody — upload to Evidence Vault."},
        {"index": 7, "title": "Post-incident review", "guidance": "DLP controls assessment, endpoint monitoring gap, insider threat programme review."},
    ],
    "lateral_movement": [
        {"index": 0, "title": "Map the movement", "guidance": "Identify every host the threat actor touched. Use CySIEM correlation data and the case graph view."},
        {"index": 1, "title": "Identify compromised credentials", "guidance": "Which accounts were used to move laterally? Force reset and revoke sessions for all of them."},
        {"index": 2, "title": "Isolate actively compromised hosts", "guidance": "Remove hosts showing active lateral movement indicators from the network segment."},
        {"index": 3, "title": "Identify initial entry point", "guidance": "Trace back to patient zero. The lateral movement started somewhere — find it and close it."},
        {"index": 4, "title": "Check crown jewel access", "guidance": "Did the actor reach tier-1 assets (domain controllers, databases, backup servers)? If yes, escalate severity to critical."},
        {"index": 5, "title": "Hunt for persistence mechanisms", "guidance": "Scheduled tasks, registry run keys, WMI subscriptions, new local admin accounts, implanted tools."},
        {"index": 6, "title": "Eradicate persistence", "guidance": "Remove all identified persistence mechanisms. Re-image where necessary."},
        {"index": 7, "title": "Verify containment", "guidance": "Confirm no further lateral movement after containment actions. Monitor CySIEM for 48h."},
    ],
    "generic": [
        {"index": 0, "title": "Confirm and classify the incident", "guidance": "Verify this is a true positive. Assign severity and type. Document initial assessment."},
        {"index": 1, "title": "Contain the threat", "guidance": "Take immediate containment steps appropriate to the incident type."},
        {"index": 2, "title": "Preserve evidence", "guidance": "Capture logs, memory, and disk images before any remediation. Upload to Evidence Vault."},
        {"index": 3, "title": "Identify scope and impact", "guidance": "What systems, data, and users are affected? What is the business impact?"},
        {"index": 4, "title": "Eradicate the threat", "guidance": "Remove malware, revoke compromised credentials, patch exploited vulnerabilities."},
        {"index": 5, "title": "Recover and restore", "guidance": "Restore from clean backups or rebuild affected systems. Validate before reconnecting."},
        {"index": 6, "title": "Notify stakeholders", "guidance": "Inform relevant internal and external parties. Assess regulatory notification obligations."},
        {"index": 7, "title": "Post-incident review", "guidance": "Document timeline, root cause, lessons learned. Update detection rules and runbooks."},
    ],
}
