from datetime import datetime
from sqlalchemy import (
    Column, BigInteger, Text, Integer, Numeric, Boolean,
    TIMESTAMP, ARRAY, UniqueConstraint, Index
)
from sqlalchemy.dialects.postgresql import JSONB
from sqlalchemy.ext.asyncio import create_async_engine, AsyncSession, async_sessionmaker
from sqlalchemy.orm import DeclarativeBase
from config import get_settings

settings = get_settings()

engine = create_async_engine(
    settings.database_url,
    pool_size=10,
    max_overflow=20,
    echo=False,
)

AsyncSessionLocal = async_sessionmaker(engine, expire_on_commit=False)


class Base(DeclarativeBase):
    pass


class Alert(Base):
    __tablename__ = "alerts"

    id              = Column(BigInteger, primary_key=True, autoincrement=True)
    wazuh_id        = Column(Text, unique=True, nullable=True)
    timestamp       = Column(TIMESTAMP(timezone=True), nullable=False)
    received_at     = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    agent_id        = Column(Text, nullable=False)
    agent_name      = Column(Text)
    agent_ip        = Column(Text)
    rule_id         = Column(Integer, nullable=False)
    rule_desc       = Column(Text)
    rule_level      = Column(Integer)
    base_score      = Column(Numeric(4, 1))
    category        = Column(Text)
    mitre_id        = Column(Text)
    mitre_tactic    = Column(Text)
    src_ip          = Column(Text)
    dst_ip          = Column(Text)
    username        = Column(Text)
    process_name    = Column(Text)
    file_path       = Column(Text)
    raw_log         = Column(Text)
    full_alert      = Column(JSONB)
    incident_id     = Column(Text, nullable=True)
    misp_ioc_match  = Column(Boolean, default=False)
    misp_event_ids  = Column(ARRAY(Integer))
    enriched        = Column(Boolean, default=False)


class Incident(Base):
    __tablename__ = "incidents"

    id                  = Column(Text, primary_key=True)
    first_seen          = Column(TIMESTAMP(timezone=True), nullable=False)
    last_seen           = Column(TIMESTAMP(timezone=True), nullable=False)
    updated_at          = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    status              = Column(Text, default="open")
    severity            = Column(Text, default="low")
    alert_count         = Column(Integer, default=0)
    affected_agents      = Column(ARRAY(Text))
    affected_agent_names = Column(ARRAY(Text))
    affected_users       = Column(ARRAY(Text))
    src_ips             = Column(ARRAY(Text))
    categories          = Column(ARRAY(Text))
    mitre_ids           = Column(ARRAY(Text))
    mitre_tactics       = Column(ARRAY(Text))
    correlated_rules    = Column(JSONB, default=list)
    ueba_flags          = Column(JSONB, default=list)
    misp_enrichment     = Column(JSONB, default=dict)
    llm_summary         = Column(Text)
    llm_remediation     = Column(Text)
    llm_generated_at    = Column(TIMESTAMP(timezone=True))
    risk_score          = Column(Numeric(5, 1), default=0)
    assigned_to         = Column(Text)
    notes               = Column(Text)
    closed_at           = Column(TIMESTAMP(timezone=True))
    false_positive_reason = Column(Text)
    # ENH-1: campaign linkage
    campaign_id    = Column(Text, nullable=True)
    campaign_peers = Column(ARRAY(Text), default=list)
    # ENH-2: kill chain tracking
    kill_chain_stage      = Column(Integer, default=0)
    kill_chain_stage_name = Column(Text, nullable=True)
    # CyCases native case management
    case_opened_at    = Column(TIMESTAMP(timezone=True), nullable=True)
    case_ack_at       = Column(TIMESTAMP(timezone=True), nullable=True)
    case_type         = Column(Text, default="generic")
    case_restricted   = Column(Boolean, default=False)
    case_mttd_seconds = Column(BigInteger, nullable=True)
    case_mtta_seconds = Column(BigInteger, nullable=True)
    # fp_probability: multi-factor false-positive probability 0–100.
    # High score = likely FP/noise.  Replaces the old single-factor confidence_score.
    fp_probability   = Column(Numeric(5, 1), nullable=True)
    # asset_tier: CMDB criticality — 1=crown jewel, 2=business critical, 3=dev/low
    asset_tier       = Column(Integer, nullable=True)
    # soar_actions: list of action objects returned by CySOAR/Node-RED
    soar_actions     = Column(JSONB, default=list)
    # ti_reputation: unified threat-intel verdict from VT + AbuseIPDB + GreyNoise + MISP
    ti_reputation    = Column(JSONB, nullable=True)
    # Phase 2: ranked attack hypotheses generated by hypothesis_engine.py
    hypotheses              = Column(JSONB, nullable=True)
    hypothesis_generated_at = Column(TIMESTAMP(timezone=True), nullable=True)
    # Phase 3: autonomous evidence collection log + coverage ratio (0–1)
    evidence_log            = Column(JSONB, nullable=True)
    evidence_collected_at   = Column(TIMESTAMP(timezone=True), nullable=True)
    evidence_coverage       = Column(Numeric(4, 2), nullable=True)
    # Phase 4: investigation confidence score (0–1) + weighted breakdown
    confidence_score        = Column(Numeric(4, 2), nullable=True)
    confidence_breakdown    = Column(JSONB, nullable=True)
    confidence_computed_at  = Column(TIMESTAMP(timezone=True), nullable=True)
    # Phase 5: structured response recommendation + SOAR dispatch state
    recommendation          = Column(JSONB, nullable=True)
    soar_dispatched         = Column(Boolean, default=False)
    soar_dispatched_at      = Column(TIMESTAMP(timezone=True), nullable=True)
    soar_dispatch_log       = Column(JSONB, nullable=True)

    __table_args__ = (
        # Speed up the common WHERE/ORDER BY patterns used by GET /incidents
        Index("ix_incidents_status",          "status"),
        Index("ix_incidents_severity",        "severity"),
        Index("ix_incidents_last_seen",       "last_seen"),
        Index("ix_incidents_status_last_seen", "status", "last_seen"),
    )


# ── Audit Log ─────────────────────────────────────────────────────────────────
# Immutable record of every status transition and manual action performed on
# incidents, ASM findings, or asset records.  Written by the ingestor pipeline
# (actor="system") and by the /transition endpoint (actor=analyst email).

class AuditLog(Base):
    __tablename__ = "audit_log"

    id           = Column(BigInteger, primary_key=True, autoincrement=True)
    entity_type  = Column(Text, nullable=False)   # "incident" | "asm_finding" | "asset"
    entity_id    = Column(Text, nullable=False)   # incident id, finding_id, or asset hostname
    action       = Column(Text, nullable=False)   # "status_change" | "case_auto_opened" | "soar_triggered" | "auto_fp" | "comment"
    from_status  = Column(Text, nullable=True)
    to_status    = Column(Text, nullable=True)
    comment      = Column(Text, nullable=True)    # mandatory for analyst-initiated transitions
    actor        = Column(Text, nullable=False)   # email or "system"
    created_at   = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    extra        = Column(JSONB, default=dict)    # fp_score, rule_ids, case_type, etc.

    __table_args__ = (
        Index("ix_audit_entity", "entity_type", "entity_id"),
    )


class UEBABaseline(Base):
    __tablename__ = "ueba_baselines"

    id                  = Column(BigInteger, primary_key=True, autoincrement=True)
    username            = Column(Text, unique=True, nullable=False)
    updated_at          = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    typical_hours       = Column(ARRAY(Integer))
    typical_agents      = Column(ARRAY(Text))
    avg_daily_events    = Column(Numeric(8, 2), default=0)
    avg_fail_rate       = Column(Numeric(5, 4), default=0)
    stddev_fail_rate    = Column(Numeric(5, 4), default=0)
    peer_group          = Column(Text)
    daily_stats         = Column(JSONB, default=list)


class UEBAAnomaly(Base):
    __tablename__ = "ueba_anomalies"

    id                  = Column(BigInteger, primary_key=True, autoincrement=True)
    detected_at         = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    username            = Column(Text, nullable=False)
    anomaly_type        = Column(Text, nullable=False)
    description         = Column(Text)
    risk_contribution   = Column(Integer, default=0)
    alert_ids           = Column(ARRAY(Text))
    incident_id         = Column(Text)
    resolved            = Column(Boolean, default=False)


class RiskScore(Base):
    __tablename__ = "risk_scores"
    __table_args__ = (UniqueConstraint("entity_id", "entity_type"),)

    id                  = Column(BigInteger, primary_key=True, autoincrement=True)
    entity_id           = Column(Text, nullable=False)
    entity_name         = Column(Text)
    entity_type         = Column(Text)
    score               = Column(Numeric(5, 1), default=0)
    level               = Column(Text)
    score_breakdown     = Column(JSONB, default=dict)
    last_calculated     = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    trend               = Column(Text, default="stable")
    prev_score          = Column(Numeric(5, 1))


class MISPIOCCache(Base):
    __tablename__ = "misp_ioc_cache"
    __table_args__ = (UniqueConstraint("ioc_value", "ioc_type"),)

    id          = Column(BigInteger, primary_key=True, autoincrement=True)
    ioc_value   = Column(Text, nullable=False)
    ioc_type    = Column(Text, nullable=False)
    cached_at   = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    expires_at  = Column(TIMESTAMP(timezone=True))
    is_hit      = Column(Boolean, default=False)
    misp_events = Column(JSONB, default=list)
    threat_level = Column(Text)
    tags        = Column(ARRAY(Text))



class HostPostureCache(Base):
    """Per-host security posture snapshot — refreshed hourly by host_service.py.

    Aggregates SCA pass rate, vulnerability counts, SIEM risk score, FIM/malware
    event counts, and compliance gap rate into a single composite posture score
    (0–100) with a letter grade.  Asset tier drives weighting in the overall
    internal posture score.
    """
    __tablename__ = "host_posture_cache"

    agent_id          = Column(Text, primary_key=True)
    agent_name        = Column(Text)
    agent_ip          = Column(Text)
    os_platform       = Column(Text)
    os_version        = Column(Text)
    wazuh_status      = Column(Text)          # active | disconnected | never_connected
    last_keepalive    = Column(TIMESTAMP(timezone=True))
    posture_score     = Column(Numeric(5, 1))
    posture_grade     = Column(Text)          # A+/A/B/C/D/F
    sca_score         = Column(Numeric(5, 1))
    sca_passed        = Column(Integer, default=0)
    sca_failed        = Column(Integer, default=0)
    sca_total         = Column(Integer, default=0)
    vuln_score        = Column(Numeric(5, 1))
    vuln_critical     = Column(Integer, default=0)
    vuln_high         = Column(Integer, default=0)
    vuln_medium       = Column(Integer, default=0)
    vuln_low          = Column(Integer, default=0)
    siem_risk         = Column(Numeric(5, 1))
    fim_event_count   = Column(Integer, default=0)
    malware_count     = Column(Integer, default=0)
    incident_count    = Column(Integer, default=0)
    compliance_score  = Column(Numeric(5, 1))
    mitre_techniques  = Column(ARRAY(Text))
    top_findings      = Column(JSONB, default=list)
    score_breakdown   = Column(JSONB, default=dict)
    asset_tier        = Column(Integer, default=3)  # 1=crown jewel, 2=biz critical, 3=standard
    computed_at       = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)

    __table_args__ = (
        Index("ix_host_posture_score",     "posture_score"),
        Index("ix_host_posture_grade",     "posture_grade"),
        Index("ix_host_posture_tier",      "asset_tier"),
        Index("ix_host_posture_computed",  "computed_at"),
    )


class CorrelationFeedback(Base):
    """ENH-6: analyst verdict on a fired incident."""
    __tablename__ = "correlation_feedback"

    id            = Column(BigInteger, primary_key=True, autoincrement=True)
    submitted_at  = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    incident_id   = Column(Text, nullable=False)
    analyst_email = Column(Text)
    verdict       = Column(Text, nullable=False)   # true_positive | false_positive | benign
    rules_fired   = Column(ARRAY(Text))
    notes         = Column(Text)


class IncidentPattern(Base):
    """Phase 6: Resolved incident patterns for historical similarity scoring.

    Stored when an incident transitions to closed/resolved.  Used by
    compute_historical_similarity() to score future incidents with matching
    technique + kill-chain stage, filling the 20% historical weight slot in
    compute_investigation_confidence().
    """
    __tablename__ = "incident_patterns"

    id                        = Column(BigInteger, primary_key=True, autoincrement=True)
    source_incident_id        = Column(Text, nullable=False)
    technique                 = Column(Text, nullable=True)         # MITRE ATT&CK ID (e.g. T1059)
    kill_chain_stage          = Column(Text, nullable=True)
    process_chain             = Column(JSONB, default=list)         # correlated rule ids + names
    payload_indicators        = Column(JSONB, default=list)         # src_ips, file_paths, usernames
    response_actions          = Column(JSONB, default=dict)         # structured recommendation used
    outcome                   = Column(Text, nullable=True)         # "resolved" | "false_positive" | "closed"
    confidence_at_resolution  = Column(Numeric(4, 2), nullable=True)
    similarity_vector         = Column(JSONB, default=dict)         # pre-computed feature vector for cosine sim
    created_at                = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)

    __table_args__ = (
        Index("ix_incident_patterns_technique",    "technique"),
        Index("ix_incident_patterns_kill_chain",   "kill_chain_stage"),
        Index("ix_incident_patterns_outcome",      "outcome"),
        Index("ix_incident_patterns_created_at",   "created_at"),
    )


class FpPattern(Base):
    """Learned false-positive patterns — fingerprints of alerts analysts repeatedly close as FP."""
    __tablename__ = "fp_patterns"

    id           = Column(BigInteger, primary_key=True, autoincrement=True)
    fingerprint  = Column(Text, nullable=False, unique=True)
    raw_sample   = Column(Text)
    agent_id     = Column(Text)          # NULL = matches any host
    rule_id      = Column(Integer)
    description  = Column(Text)
    close_count  = Column(Integer, default=0)
    threshold    = Column(Integer, default=5)
    auto_close   = Column(Boolean, default=False)
    last_seen    = Column(TIMESTAMP(timezone=True))
    created_at   = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    updated_at   = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    created_by   = Column(Text)

    __table_args__ = (
        Index("ix_fp_patterns_fingerprint", "fingerprint"),
        Index("ix_fp_patterns_auto_close",  "auto_close"),
    )


class RuleToggle(Base):
    """Enable/disable state for a BUILT-IN rule (correlator.py's CR-xxx classes or
    ueba.py's numbered anomaly_type detectors). Absence of a row means enabled —
    this table only ever needs to hold the rules an operator has explicitly
    turned off, so a fresh install has zero rows and every rule runs exactly as
    it did before this feature existed."""
    __tablename__ = "rule_toggles"
    __table_args__ = (UniqueConstraint("rule_kind", "rule_key"),)

    id         = Column(BigInteger, primary_key=True, autoincrement=True)
    rule_kind  = Column(Text, nullable=False)   # "correlation" | "ueba"
    rule_key   = Column(Text, nullable=False)   # e.g. "CR-001" or "off_hours_login"
    enabled    = Column(Boolean, default=True, nullable=False)
    updated_at = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    updated_by = Column(Text)


class CustomCorrelationRule(Base):
    """User-authored correlation rule, evaluated alongside the built-in CR-001..055
    rules in correlator.py. Unlike the built-ins (which pattern-match specific
    attack chains in Python), a custom rule is a generic "N alerts matching these
    field conditions within a time window" pattern — see custom_rules_engine.py."""
    __tablename__ = "custom_correlation_rules"

    id                 = Column(BigInteger, primary_key=True, autoincrement=True)
    rule_key           = Column(Text, nullable=False, unique=True)
    name               = Column(Text, nullable=False)
    description        = Column(Text)
    enabled            = Column(Boolean, default=True, nullable=False)
    conditions         = Column(JSONB, nullable=False, default=list)   # [{field, op, value}, ...] ANDed
    window_minutes     = Column(Integer, default=15, nullable=False)
    min_count          = Column(Integer, default=1, nullable=False)
    severity_override  = Column(Text)   # "low"|"medium"|"high"|"critical" or NULL = don't escalate
    tags               = Column(ARRAY(Text), default=list)
    created_at         = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    updated_at         = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    created_by         = Column(Text)


class CustomUebaRule(Base):
    """User-authored UEBA anomaly rule, evaluated alongside the built-in
    detectors in ueba.py. Same condition/window/count shape as
    CustomCorrelationRule but scoped to one entity (user or host) — see
    custom_rules_engine.py."""
    __tablename__ = "custom_ueba_rules"

    id                 = Column(BigInteger, primary_key=True, autoincrement=True)
    rule_key           = Column(Text, nullable=False, unique=True)
    name               = Column(Text, nullable=False)
    description        = Column(Text)
    enabled            = Column(Boolean, default=True, nullable=False)
    conditions         = Column(JSONB, nullable=False, default=list)
    window_minutes     = Column(Integer, default=15, nullable=False)
    min_count          = Column(Integer, default=1, nullable=False)
    entity_type        = Column(Text, default="user", nullable=False)  # "user" | "host"
    anomaly_type       = Column(Text, nullable=False)   # display label, e.g. "custom_data_hoarding"
    risk_contribution  = Column(Integer, default=40, nullable=False)
    created_at         = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    updated_at         = Column(TIMESTAMP(timezone=True), default=datetime.utcnow)
    created_by         = Column(Text)


async def write_audit(
    db,
    entity_type: str,
    entity_id: str,
    action: str,
    actor: str,
    from_status: str | None = None,
    to_status: str | None = None,
    comment: str | None = None,
    extra: dict | None = None,
) -> None:
    """Append an immutable audit entry to the audit_log table."""
    from datetime import datetime, timezone
    entry = AuditLog(
        entity_type = entity_type,
        entity_id   = entity_id,
        action      = action,
        actor       = actor,
        from_status = from_status,
        to_status   = to_status,
        comment     = comment,
        extra       = extra or {},
        created_at  = datetime.now(timezone.utc),
    )
    db.add(entry)


async def get_db():
    async with AsyncSessionLocal() as session:
        try:
            yield session
        finally:
            await session.close()


async def init_db():
    """Create tables if they don't exist (init.sql is primary, this is fallback)."""
    try:
        async with engine.begin() as conn:
            await conn.run_sync(Base.metadata.create_all)
            # Phase 1 migration: add ti_reputation column to existing incidents table
            await conn.execute(
                __import__("sqlalchemy").text(
                    "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS ti_reputation JSONB"
                )
            )
            # Phase 2 migration: hypothesis engine columns
            await conn.execute(
                __import__("sqlalchemy").text(
                    "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS hypotheses JSONB"
                )
            )
            await conn.execute(
                __import__("sqlalchemy").text(
                    "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS "
                    "hypothesis_generated_at TIMESTAMPTZ"
                )
            )
            # Phase 3 migration: evidence collection columns
            for col_ddl in [
                "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS evidence_log JSONB",
                "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS evidence_collected_at TIMESTAMPTZ",
                "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS evidence_coverage NUMERIC(4,2)",
            ]:
                await conn.execute(__import__("sqlalchemy").text(col_ddl))
            # Phase 4 migration: investigation confidence columns
            for col_ddl in [
                "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS confidence_score NUMERIC(4,2)",
                "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS confidence_breakdown JSONB",
                "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS confidence_computed_at TIMESTAMPTZ",
            ]:
                await conn.execute(__import__("sqlalchemy").text(col_ddl))
            # Phase 5 migration: structured recommendation + SOAR dispatch state
            for col_ddl in [
                "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS recommendation JSONB",
                "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS soar_dispatched BOOLEAN DEFAULT FALSE",
                "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS soar_dispatched_at TIMESTAMPTZ",
                "ALTER TABLE incidents ADD COLUMN IF NOT EXISTS soar_dispatch_log JSONB",
            ]:
                await conn.execute(__import__("sqlalchemy").text(col_ddl))
            # Phase 6 migration: incident pattern memory table
            await conn.execute(__import__("sqlalchemy").text("""
                CREATE TABLE IF NOT EXISTS incident_patterns (
                    id                       BIGSERIAL PRIMARY KEY,
                    source_incident_id       TEXT NOT NULL,
                    technique                TEXT,
                    kill_chain_stage         TEXT,
                    process_chain            JSONB DEFAULT '[]',
                    payload_indicators       JSONB DEFAULT '[]',
                    response_actions         JSONB DEFAULT '{}',
                    outcome                  TEXT,
                    confidence_at_resolution NUMERIC(4,2),
                    similarity_vector        JSONB DEFAULT '{}',
                    created_at               TIMESTAMPTZ DEFAULT NOW()
                )
            """))
            await conn.execute(__import__("sqlalchemy").text(
                "CREATE INDEX IF NOT EXISTS ix_incident_patterns_technique "
                "ON incident_patterns (technique)"
            ))
            await conn.execute(__import__("sqlalchemy").text(
                "CREATE INDEX IF NOT EXISTS ix_incident_patterns_kill_chain "
                "ON incident_patterns (kill_chain_stage)"
            ))
    except Exception as exc:
        import logging
        logging.getLogger("cysiemstack").critical(
            "DATABASE CONNECTION FAILED — check DATABASE_URL in /opt/cycentra/cysiemstack.env\n"
            "  Error: %s\n"
            "  Ensure PostgreSQL is running on 127.0.0.1:5433 and corruser has access.",
            exc,
        )
        raise
