"""
Regression tests — CySIEM (Wazuh) SSO Authentication

Bug: Users authenticated via the CyCentra360 Portal received
     {"statusCode":401,"error":"Unauthorized","message":"Unauthorized"}
     when accessing CySIEM (Wazuh Dashboard) via SSO, while CySOAR
     SSO worked correctly.

Root causes fixed:
  1. `cysiem` OIDC client was removed from OIDC_CLIENTS in config.py even
     though CYSIEM_OIDC_SECRET was still generated by setup.sh. No OIDC
     fallback path existed for the Wazuh Dashboard.
  2. securityadmin.sh was called without an OpenSearch readiness check, so
     it silently failed when the indexer hadn't finished starting — leaving
     proxy_auth_domain disabled and the all_access rolesmapping unset.
  3. The rolesmapping had no REST API fallback; only securityadmin.sh was
     tried, which requires JVM and can fail for unrelated reasons.

These tests FAIL on code before the fix and PASS after.
"""

import base64
import json
import os
import sys
import time

sys.path.insert(0, os.path.join(os.path.dirname(__file__), '..', '..', 'backend'))

import pytest

# ── Environment bootstrapping (must happen before any app import) ─────────────
os.environ.setdefault("CYCENTRA_ENV",       "test")
os.environ.setdefault("JWT_SECRET",          "testsecret-siem-sso")
os.environ.setdefault("BASE_DOMAIN",         "cycentra.test")
os.environ.setdefault("BASE_URL",            "https://cyasm.cycentra.test")
os.environ.setdefault("FRONTEND_URL",        "https://cysoc.cycentra.test")
os.environ.setdefault("DATABASE_URL",        "sqlite:///:memory:")
os.environ.setdefault("SECRET_KEY",          "test-secret-key-siem")
os.environ.setdefault("OAUTH2PROXY_SECRET",  "test-oauth2proxy-secret")
os.environ.setdefault("CYSIEM_OIDC_SECRET",  "test-cysiem-oidc-secret")


# ── Helpers ───────────────────────────────────────────────────────────────────

def _basic_header(client_id: str, client_secret: str) -> str:
    raw = f"{client_id}:{client_secret}"
    return "Basic " + base64.b64encode(raw.encode()).decode()


def _seed_auth_code(flask_app, code: str, client_id: str, email: str,
                    redirect_uri: str = "https://cysoc.cycentra.test/oauth2/callback"):
    """Inject a valid auth code directly into the provider's in-memory store."""
    from blueprints.oidc import provider as oidc_prov
    oidc_prov._AUTH_CODES[code] = {
        "email":        email,
        "client_id":    client_id,
        "redirect_uri": redirect_uri,
        "nonce":        "test-nonce",
        "expires":      time.time() + 300,
    }


def _seed_rbac(flask_app, email: str, role: str):
    """Inject a user → role mapping for the test."""
    from blueprints.rbac import manager as rbac_mgr
    orig_fn = rbac_mgr._load_rbac

    def _fake_load():
        return {email: {"role": role}}

    rbac_mgr._load_rbac = _fake_load
    yield
    rbac_mgr._load_rbac = orig_fn


# ── Fixtures ──────────────────────────────────────────────────────────────────

@pytest.fixture(scope="module")
def flask_app():
    from app import app
    app.config["TESTING"]    = True
    app.config["SECRET_KEY"] = "test-secret-key-siem"
    return app


@pytest.fixture()
def client(flask_app):
    return flask_app.test_client()


# ─────────────────────────────────────────────────────────────────────────────
# 1. cysiem OIDC CLIENT REGISTRATION
# ─────────────────────────────────────────────────────────────────────────────

class TestCySiemOidcClientRegistered:
    """
    The `cysiem` OIDC client MUST be registered in OIDC_CLIENTS.
    Before the fix, it was removed and CYSIEM_OIDC_SECRET was generated
    but never consumed — leaving no Wazuh Dashboard OIDC fallback path.
    """

    def test_cysiem_client_in_oidc_clients(self):
        """cysiem must appear in OIDC_CLIENTS."""
        from core.config import OIDC_CLIENTS
        assert "cysiem" in OIDC_CLIENTS, (
            "cysiem OIDC client is missing from OIDC_CLIENTS — "
            "Wazuh Dashboard direct-OIDC SSO path is broken"
        )

    def test_cysiem_client_has_secret(self):
        """CYSIEM_OIDC_SECRET must be wired into the cysiem client."""
        from core.config import OIDC_CLIENTS
        assert OIDC_CLIENTS.get("cysiem", {}).get("client_secret") == \
               os.environ["CYSIEM_OIDC_SECRET"], (
            "cysiem client_secret does not match CYSIEM_OIDC_SECRET env var"
        )

    def test_cysiem_client_redirect_uri_points_to_wazuh_dashboard(self):
        """cysiem redirect_uri must point to Wazuh Dashboard OIDC callback."""
        from core.config import OIDC_CLIENTS
        uris = OIDC_CLIENTS.get("cysiem", {}).get("redirect_uris", [])
        assert any("cysiem" in u and "/auth/openid/login" in u for u in uris), (
            f"No Wazuh Dashboard OIDC callback URI found in cysiem.redirect_uris: {uris}"
        )

    def test_cysiem_client_allowed_roles_covers_portal_roles(self):
        """Portal users with admin/analyst/viewer roles must be able to use cysiem client."""
        from core.config import OIDC_CLIENTS
        allowed = set(OIDC_CLIENTS.get("cysiem", {}).get("allowed_roles", []))
        required = {"admin", "analyst", "viewer"}
        assert required.issubset(allowed), (
            f"cysiem.allowed_roles is missing portal roles: {required - allowed}"
        )

    def test_oauth2proxy_client_registered(self):
        """oauth2proxy IAP client must also be registered (CySIEM nginx gate)."""
        from core.config import OIDC_CLIENTS
        assert "oauth2proxy" in OIDC_CLIENTS


# ─────────────────────────────────────────────────────────────────────────────
# 2. RS256 TOKEN FOR cysiem CLIENT
# ─────────────────────────────────────────────────────────────────────────────

class TestCySiemRS256Token:
    """
    OpenSearch Security's OIDC auth domain requires RS256 (asymmetric JWT
    verifiable via JWKS). The cysiem client must receive RS256 tokens.
    Before the fix, cysiem was in _RS256_CLIENTS but not in OIDC_CLIENTS,
    so no token was ever issued to Wazuh Dashboard.
    """

    def test_cysiem_token_exchange_returns_200(self, client, flask_app):
        """Full code→token exchange for cysiem client must succeed."""
        from core.config import OIDC_CLIENTS
        secret   = OIDC_CLIENTS["cysiem"]["client_secret"]
        code     = "test_cysiem_token_rs256"
        email    = "analyst@test.local"
        redirect = OIDC_CLIENTS["cysiem"]["redirect_uris"][0]

        _seed_auth_code(flask_app, code, "cysiem", email, redirect_uri=redirect)

        resp = client.post(
            "/oidc/token",
            data={
                "grant_type":    "authorization_code",
                "code":          code,
                "client_id":     "cysiem",
                "client_secret": secret,
            },
        )
        assert resp.status_code == 200, (
            f"cysiem OIDC token exchange failed with {resp.status_code}: {resp.data}"
        )
        body = json.loads(resp.data)
        assert "id_token"     in body, f"id_token missing: {body}"
        assert "access_token" in body, f"access_token missing: {body}"

    def test_cysiem_token_is_rs256_when_rsa_available(self, client, flask_app):
        """id_token for cysiem must use RS256 algorithm when RSA key is available."""
        from blueprints.oidc import provider as oidc_prov
        if not (oidc_prov._JWT_AVAILABLE and oidc_prov._RSA_AVAILABLE):
            pytest.skip("PyJWT or cryptography not installed — RS256 unavailable")

        from core.config import OIDC_CLIENTS
        secret   = OIDC_CLIENTS["cysiem"]["client_secret"]
        code     = "test_cysiem_token_alg"
        email    = "admin@test.local"
        redirect = OIDC_CLIENTS["cysiem"]["redirect_uris"][0]

        _seed_auth_code(flask_app, code, "cysiem", email, redirect_uri=redirect)

        resp = client.post(
            "/oidc/token",
            data={
                "grant_type":    "authorization_code",
                "code":          code,
                "client_id":     "cysiem",
                "client_secret": secret,
            },
        )
        assert resp.status_code == 200
        body = json.loads(resp.data)

        # Decode header (first segment of JWT) without verification
        header_b64 = body["id_token"].split(".")[0]
        # Re-pad: base64url strips trailing '='; (-len % 4) gives 0–3 '=' chars needed
        base64_padding = "=" * (-len(header_b64) % 4)
        header         = json.loads(base64.urlsafe_b64decode(header_b64 + base64_padding))
        assert header.get("alg") == "RS256", (
            f"cysiem id_token must use RS256 (got {header.get('alg')}). "
            "OpenSearch Security OIDC domain requires RS256 — HS256 will not verify via JWKS."
        )
        assert "kid" in header, "RS256 id_token must include a 'kid' header for JWKS lookup"

    def test_cysiem_token_contains_email_and_roles_claims(self, client, flask_app):
        """id_token must contain email, sub, and roles claims for OpenSearch role mapping."""
        from core.config import OIDC_CLIENTS
        secret   = OIDC_CLIENTS["cysiem"]["client_secret"]
        code     = "test_cysiem_token_claims"
        email    = "viewer@test.local"
        redirect = OIDC_CLIENTS["cysiem"]["redirect_uris"][0]

        _seed_auth_code(flask_app, code, "cysiem", email, redirect_uri=redirect)

        resp = client.post(
            "/oidc/token",
            data={
                "grant_type":    "authorization_code",
                "code":          code,
                "client_id":     "cysiem",
                "client_secret": secret,
            },
        )
        assert resp.status_code == 200
        body      = json.loads(resp.data)
        id_token  = body["id_token"]

        # Decode payload (second segment) without verification
        payload_b64 = id_token.split(".")[1]
        # Re-pad: base64url strips trailing '='; (-len % 4) gives 0–3 '=' chars needed
        base64_padding = "=" * (-len(payload_b64) % 4)
        payload        = json.loads(base64.urlsafe_b64decode(payload_b64 + base64_padding))

        assert payload.get("sub")   == email,   f"sub mismatch: {payload}"
        assert payload.get("email") == email,   f"email mismatch: {payload}"
        assert "roles" in payload,              f"roles claim missing: {payload}"
        assert payload.get("aud")   == "cysiem", f"aud must be 'cysiem': {payload}"

    def test_cysiem_wrong_secret_returns_401(self, client, flask_app):
        """Wrong client_secret for cysiem must be rejected."""
        code = "test_cysiem_bad_secret"
        _seed_auth_code(flask_app, code, "cysiem", "any@test.local",
                        redirect_uri="https://cysiem.cycentra.test/auth/openid/login")
        resp = client.post(
            "/oidc/token",
            data={
                "grant_type":    "authorization_code",
                "code":          code,
                "client_id":     "cysiem",
                "client_secret": "wrong-secret-value",
            },
        )
        assert resp.status_code == 401, (
            f"Expected 401 for bad cysiem secret, got {resp.status_code}"
        )


# ─────────────────────────────────────────────────────────────────────────────
# 3. JWKS ENDPOINT (required by OpenSearch Security for RS256 verification)
# ─────────────────────────────────────────────────────────────────────────────

class TestJwksEndpoint:
    """
    Wazuh Dashboard's OpenSearch Security OIDC domain fetches the public key
    from /oidc/jwks to verify id_tokens. If this returns an empty key set,
    ALL CySIEM OIDC logins fail with signature verification errors.
    """

    def test_jwks_returns_200(self, client):
        resp = client.get("/oidc/jwks")
        assert resp.status_code == 200

    def test_jwks_returns_keys_array(self, client):
        resp = client.get("/oidc/jwks")
        body = json.loads(resp.data)
        assert "keys" in body, f"JWKS response missing 'keys': {body}"

    def test_jwks_key_has_required_rsa_fields_when_available(self, client):
        """When RSA is available, JWKS must contain a valid RSA JWK."""
        from blueprints.oidc import provider as oidc_prov
        if not oidc_prov._RSA_AVAILABLE:
            pytest.skip("RSA not available in this environment")

        resp = client.get("/oidc/jwks")
        body = json.loads(resp.data)
        assert len(body["keys"]) >= 1, "JWKS must contain at least one key when RSA is available"

        key = body["keys"][0]
        for field in ("kty", "use", "alg", "kid", "n", "e"):
            assert field in key, f"JWK missing required field '{field}': {key}"
        assert key["kty"] == "RSA",    f"Expected RSA key type, got {key['kty']}"
        assert key["alg"] == "RS256",  f"Expected RS256, got {key['alg']}"
        assert key["use"] == "sig",    f"Expected 'sig' use, got {key['use']}"

    def test_discovery_advertises_rs256(self, client):
        """OIDC discovery must advertise RS256 so Wazuh Dashboard configures the right alg."""
        resp = client.get("/oidc/.well-known/openid-configuration")
        assert resp.status_code == 200
        body = json.loads(resp.data)
        algs = body.get("id_token_signing_alg_values_supported", [])
        assert "RS256" in algs, (
            f"Discovery must advertise RS256 for OpenSearch Security OIDC domain: {algs}"
        )


# ─────────────────────────────────────────────────────────────────────────────
# 4. ROLE-BASED ACCESS — who can authenticate via each SSO path
# ─────────────────────────────────────────────────────────────────────────────

class TestCySiemRoleAccess:
    """
    Verify which portal roles can access which OIDC client.

    IAP gate (oauth2proxy): all portal roles — everyone who can log in to the
    portal can reach cysiem.DOMAIN through the nginx IAP.
    Wazuh Dashboard OIDC (cysiem): only admin / analyst / viewer — the SIEM-
    capable roles. cysoar role accounts do not have CySIEM access.
    """

    def _mock_role(self, email: str, role: str):
        """Return a context-manager-like that patches _load_rbac."""
        import contextlib
        from blueprints.rbac import manager as rbac_mgr

        @contextlib.contextmanager
        def _ctx():
            orig = rbac_mgr._load_rbac
            rbac_mgr._load_rbac = lambda: {email: {"role": role}}
            try:
                yield
            finally:
                rbac_mgr._load_rbac = orig

        return _ctx()

    @pytest.mark.parametrize("role", ["admin", "analyst", "viewer"])
    def test_portal_role_can_access_cysiem_oidc_client(self, role):
        """Portal SIEM roles (admin/analyst/viewer) must be allowed for cysiem client."""
        email = f"{role}@test.local"
        with self._mock_role(email, role):
            from blueprints.rbac.manager import user_can_access_client
            assert user_can_access_client(email, "cysiem"), (
                f"Role '{role}' must be permitted to use cysiem OIDC client"
            )

    @pytest.mark.parametrize("role", ["cysoar"])
    def test_non_siem_role_denied_cysiem_oidc_client(self, role):
        """Roles without CySIEM app access must NOT use cysiem OIDC client directly."""
        email = f"{role}@test.local"
        with self._mock_role(email, role):
            from blueprints.rbac.manager import user_can_access_client
            assert not user_can_access_client(email, "cysiem"), (
                f"Role '{role}' must NOT be permitted to use cysiem OIDC client directly — "
                "these roles have no CySIEM app access in ROLE_APPS"
            )

    @pytest.mark.parametrize("role", ["admin", "analyst", "viewer", "cysoar"])
    def test_all_portal_roles_can_use_oauth2proxy_iap_gate(self, role):
        """ALL portal roles must be allowed through the oauth2proxy IAP gate.

        The nginx IAP gate (oauth2proxy) should not block any logged-in portal user
        from reaching cysiem.DOMAIN — role-level filtering happens within the
        Dashboard, not at the IAP layer.
        """
        email = f"{role}@test.local"
        with self._mock_role(email, role):
            from blueprints.rbac.manager import user_can_access_client
            assert user_can_access_client(email, "oauth2proxy"), (
                f"Role '{role}' must be permitted through the oauth2proxy IAP gate "
                "— otherwise CySIEM SSO breaks for all non-admin users"
            )

    def test_unknown_user_defaults_to_viewer_and_can_access_cysiem(self):
        """Unregistered users default to 'viewer' and must be able to reach cysiem."""
        from blueprints.rbac.manager import user_can_access_client
        # 'nobody@unknown.local' has no RBAC entry — defaults to 'viewer'
        assert user_can_access_client("nobody@unknown.local", "oauth2proxy"), (
            "New/unregistered users default to viewer role and must pass the oauth2proxy gate"
        )


# ─────────────────────────────────────────────────────────────────────────────
# 5. USERINFO ENDPOINT (oauth2-proxy calls this after token exchange)
# ─────────────────────────────────────────────────────────────────────────────

class TestUserinfoForCySiem:
    """
    After the OIDC token exchange, oauth2-proxy calls /oidc/userinfo with the
    access_token to get the user's email for X-Auth-Request-Email.
    This endpoint must return the correct email so nginx can set X-Proxy-User.
    """

    def test_userinfo_returns_email_after_cysiem_token_exchange(self, client, flask_app):
        """
        Full flow: token exchange for oauth2proxy → userinfo returns email.
        This email becomes X-Auth-Request-Email → $proxy_user → X-Proxy-User
        header sent to Wazuh Dashboard.
        """
        from core.config import OIDC_CLIENTS
        secret   = OIDC_CLIENTS["oauth2proxy"]["client_secret"]
        code     = "test_userinfo_email_flow"
        email    = "analyst@siem-test.local"
        redirect = OIDC_CLIENTS["oauth2proxy"]["redirect_uris"][0]

        _seed_auth_code(flask_app, code, "oauth2proxy", email, redirect_uri=redirect)

        # Exchange code for tokens
        token_resp = client.post(
            "/oidc/token",
            data={
                "grant_type":    "authorization_code",
                "code":          code,
                "client_id":     "oauth2proxy",
                "client_secret": secret,
            },
        )
        assert token_resp.status_code == 200, \
            f"Token exchange failed: {token_resp.data}"
        access_token = json.loads(token_resp.data)["access_token"]

        # Fetch userinfo (as oauth2-proxy would, server-to-server, no browser cookie)
        info_resp = client.get(
            "/oidc/userinfo",
            headers={"Authorization": f"Bearer {access_token}"},
        )
        assert info_resp.status_code == 200, \
            f"Userinfo failed: {info_resp.data}"
        info = json.loads(info_resp.data)
        assert info.get("email") == email, (
            f"Userinfo email mismatch — X-Auth-Request-Email would be wrong: {info}"
        )
        assert info.get("sub") == email, f"sub mismatch: {info}"

    def test_userinfo_invalid_token_returns_401(self, client):
        """Expired/invalid access token must return 401 — not 500."""
        resp = client.get(
            "/oidc/userinfo",
            headers={"Authorization": "Bearer invalidtoken12345"},
        )
        assert resp.status_code == 401


# ─────────────────────────────────────────────────────────────────────────────
# 6. AUTHORIZE ENDPOINT — session-based flow for CySIEM SSO
# ─────────────────────────────────────────────────────────────────────────────

class TestAuthorizeForCySiem:
    """
    When a portal-authenticated user reaches cysiem.DOMAIN, the nginx IAP gate
    redirects to /oidc/authorize. This endpoint MUST issue a code if the Flask
    session has a valid user_email; otherwise it must redirect to the portal login.
    """

    @pytest.fixture(autouse=True)
    def _relax_cookie_settings(self, flask_app):
        """
        Override session cookie domain/secure settings for test client.
        Production uses SESSION_COOKIE_DOMAIN=".cycentra.test" + SECURE=True.
        The test client sends plain HTTP to 'localhost', so the domain-scoped
        secure cookie is never included in requests — causing session.get("user_email")
        to return None.  Set domain=None and SECURE=False for this test class only.
        """
        orig = {
            "SESSION_COOKIE_DOMAIN": flask_app.config.get("SESSION_COOKIE_DOMAIN"),
            "SESSION_COOKIE_SECURE": flask_app.config.get("SESSION_COOKIE_SECURE"),
        }
        flask_app.config["SESSION_COOKIE_DOMAIN"] = None
        flask_app.config["SESSION_COOKIE_SECURE"] = False
        yield
        flask_app.config.update(orig)

    def test_authorize_redirects_to_portal_when_not_logged_in(self, client):
        """Unauthenticated request to /oidc/authorize must redirect to portal, not 401."""
        from core.config import OIDC_CLIENTS
        redirect_uri = OIDC_CLIENTS["oauth2proxy"]["redirect_uris"][0]
        resp = client.get(
            "/oidc/authorize",
            query_string={
                "client_id":     "oauth2proxy",
                "redirect_uri":  redirect_uri,
                "response_type": "code",
                "state":         "test-state",
            },
        )
        # Must redirect (302/301) to the portal for login — never return 401
        assert resp.status_code in (301, 302), (
            f"Unauthenticated /oidc/authorize should redirect (got {resp.status_code}). "
            "Returning 401 here would break the SSO login loop."
        )
        location = resp.headers.get("Location", "")
        assert "oidc_return" in location, (
            f"Redirect should carry oidc_return param for post-login flow: {location}"
        )

    def test_authorize_issues_code_when_logged_in(self, client, flask_app):
        """Portal-authenticated user must get an auth code — the SSO implicit grant."""
        from core.config import OIDC_CLIENTS, FRONTEND_URL
        redirect_uri = OIDC_CLIENTS["oauth2proxy"]["redirect_uris"][0]

        with client.session_transaction() as sess:
            sess["user_email"] = "admin@siem-test.local"
            sess["user_name"]  = "SIEM Admin"

        resp = client.get(
            "/oidc/authorize",
            query_string={
                "client_id":     "oauth2proxy",
                "redirect_uri":  redirect_uri,
                "response_type": "code",
                "state":         "siem-sso-state",
            },
        )
        assert resp.status_code in (301, 302), \
            f"Logged-in authorize must redirect with code (got {resp.status_code})"
        location = resp.headers.get("Location", "")
        assert "code=" in location, (
            f"Authorize response must include 'code=' for token exchange: {location}"
        )
        assert "siem-sso-state" in location, \
            f"State parameter must be echoed back: {location}"

    def test_cysiem_direct_oidc_authorize_issues_code_when_logged_in(self, client, flask_app):
        """
        When Wazuh Dashboard is configured for openid auth type (OIDC fallback path),
        it sends the user to /oidc/authorize?client_id=cysiem. A logged-in portal
        user must receive an auth code — not be blocked.
        """
        from core.config import OIDC_CLIENTS
        redirect_uri = OIDC_CLIENTS["cysiem"]["redirect_uris"][0]

        with client.session_transaction() as sess:
            sess["user_email"] = "analyst@siem-test.local"

        resp = client.get(
            "/oidc/authorize",
            query_string={
                "client_id":     "cysiem",
                "redirect_uri":  redirect_uri,
                "response_type": "code",
                "state":         "cysiem-state",
            },
        )
        assert resp.status_code in (301, 302)
        location = resp.headers.get("Location", "")
        assert "code=" in location, (
            f"cysiem direct OIDC authorize must issue code: {location}"
        )

    def test_authorize_denies_unknown_client(self, client, flask_app):
        """Unknown client_id must return 400, not 500."""
        with client.session_transaction() as sess:
            sess["user_email"] = "admin@siem-test.local"

        resp = client.get(
            "/oidc/authorize",
            query_string={
                "client_id":     "unknown_client",
                "redirect_uri":  "https://evil.com/callback",
                "response_type": "code",
                "state":         "x",
            },
        )
        assert resp.status_code == 400

    def test_authorize_denies_invalid_redirect_uri(self, client, flask_app):
        """Redirect URI not registered for the client must be rejected."""
        with client.session_transaction() as sess:
            sess["user_email"] = "admin@siem-test.local"

        resp = client.get(
            "/oidc/authorize",
            query_string={
                "client_id":     "cysiem",
                "redirect_uri":  "https://attacker.com/steal-token",
                "response_type": "code",
                "state":         "x",
            },
        )
        assert resp.status_code == 400, (
            f"Unregistered redirect_uri must be rejected (got {resp.status_code})"
        )
